
GET http://localhost:7000/users

###

GET http://localhost:7000/users/658cf61084f1ad243ec84bd7

###

POST http://localhost:7000/users
Content-Type: application/json

{
	"name": "kat shpak",
	"email": "email@example.com",
    "password": "password"
}


###


DELETE http://localhost:7000/users/658cf61084f1ad243ec84bd7

###

PATCH http://localhost:7000/users/658cf61084f1ad243ec84bd7
Content-Type: application/json

{
	"name": "New Name"
}
